# Dependencies
highlighter:      rouge

# Permalinks
permalink:        :title/

author:
  name:           'Dipanjan Mukherjee'
  url:            https://twitter.com/DipanjanMu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/schatten/dipanjan.blog

sass:
  sass_dir: public/scss